language: java
jdk:
- openjdk8
script:
  - ./scripts/package.sh
deploy:
  provider: releases
  api_key:
    secure: N/ESp6hxr1T+IEvCQe/gAVUbdPS8Hov2oPcr32iAOrMR/QivkXYaFs4epDd4+U32APqJktZglbMXKmysWz/XrAXTSEObRJbevCLIGrB02s/OStIah2PSR2DGVc86ybLMr0EahDpgthFN28vryFQRsDrpeAuNr96viBdKzLIw8sA3qe/jJhIhmUkwtwTuNtl4WBMijOrA/mAll/f+eEgJkGYQfVFY5KeLQDgkS3S36AFGh6caWH/iUYDwa5CvooRIvWn47uUapV+7DLSjQlUfV8XS4+o+eeFlF0pevSmpdB/e8vYOwGOmgdchIJCwYdLwsXCcb5c7FmLU3Zj1gpzn0cVRX9Qds6Lz6CRD5f1pb7YA1w7Ka67AFmctpZrKjEt2wPj9iFSIvu8ka51r3l/8f9RJTCbAMLv+3GNyKcc3aBYpnXxjlQCq7J2Y7Qt85YzS7V9XKfRH7xBRt5uq5F6FGs2gOCGmqiwAX84++B2cQHI9ErbTYByJAxOTAQ46RcQcQf3Hq4H2+Yz2ZZ5tpZZv4VYujk7rD4w3435BMVP1hOW80yOjoVtCmolbG9pysBmt5TlshDcg2tbZ+nlv/OwPhien3nPsoaLRL86kx6XG+MvHsd5G/b6oUr22Jwuw0PQmdqTRgSe9SS2HhxO+Cqp0qRnuqk+xZsWaT9vZCUcSl3o=
  skip_cleanup: true
  file: build/sandbox-runtime.tar
  on:
    tags: true
    repo: getsandbox/sandbox
